main:
	g++ -std=c++20 main.cpp -o main.out

old:
	g++ -std=c++20 old.cpp -o old.out

banch:
	g++ -std=c++20 -O2 main.cpp -o main.out
	g++ -O2 naive.cpp -o naive.out
	g++ -O2 generator.cpp -o generator.out