SHELL = /bin/bash

main:
	g++ main.cpp -o main -Wall -Werror	

banch filename:
	make main
	g++ std_sort.cpp -o std_sort -Wall -Werror
	g++ banch.cpp -o banch -Wall -Werror
	g++ make_test.cpp -o make_test -Wall -Werror
